### PR TITLE
HomeAssistant example for 1 pump tubs

### PR DESCRIPTION
**Pull request by s1dave-web**
I have made a HomeAssistant example for use with tubs that only have 1 pump

Use of buttons is required to cycle the pump modes

### CODE REVIEW

**Comment by netmindz** [comment]
Do you have a dual speed pump then? My (untested) code tried to send a toggle of the state if required

**Comment by s1dave-web** [comment]
Yes it has only 1 "jets" button that toggles between off > half speed > full speed > off

**Comment by netmindz** [comment]
Ok, in the code for my own tub (GL series) I use a `select` rather than `switch` to handle dual-speed pumps, this library however only returns displayPump1 as a `bool`, so are you able to read the status in a way that lets you know off/low/high or is the info for the GS series returns really designed only for the status LED that is just on/off ?

**Comment by netmindz** [comment]
p.s the Arduino IDE expects the .ino file to match the directory name, so this new example needs it's own directory

**Comment by s1dave-web** [comment]
> Ok, in the code for my own tub (GL series) I use a `select` rather than `switch` to handle dual-speed pumps, this library however only returns displayPump1 as a `bool`, so are you able to read the status in a way that lets you know off/low/high or is the info for the GS series returns really designed only for the status LED that is just on/off ?

Only getting state as on/off unfortunately

**Comment by netmindz** [comment]
If there is no way to see the state of the pump, then button and binary sensor would be the right approach

**Comment by s1dave-web** [comment]
@MagnusPer is speed detection possible? would it require oscilloscope to monitor for bit changes between low/high speed on pump? 

Also wondering if there is anyway to detect what mode the tub is in Eco/Standard/Sleep

**Comment by MagnusPer** [comment]
@s1dave-web  - 
**pump speed** I do not have two speed pumps in my SPA so I don't know if the communication indicates the status. But if the display indicates in some way the speed there must be something triggering this information.

**mode** There is technical possibility to get this information by first "press" the mode button and then read text shown in display. I have not however had the need for such use-case.

**Pull request merged**
