### PR TITLE
Update Balboa_GS_HomeAssistant.ino

### PR DESCRIPTION
**Pull request by s1dave-web**
Changes to make Temp Up, Temp Down and Lights work in Home Assistant

### CODE REVIEW

**Review by netmindz — APPROVED** [review]

**Comment by MagnusPer** [comment]
@s1dave-web or @netmindz There is some merged conflicts in this PR, please resolve

**Comment by MagnusPer** [comment]
Please resolve this PR

**Comment by netmindz** [comment]
Why have you closed @MagnusPer it has important fixes

**Comment by MagnusPer** [comment]
@netmindz it had merge conflicts, but it was a mistake to close from my side. please push a new PR

**Pull request closed without merging**
